/**
 * ToDo Action Types
 */
export const TODO_FETCH_REQUEST = 'TODO_FETCH_REQUEST';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const TODO_FETCH_ERROR = 'TODO_FETCH_ERROR';
export const TODO_ADD_REQUEST = 'TODO_ADD_REQUEST';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_ERROR = 'TODO_ADD_ERROR';
export const TODO_UPDATE_REQUEST = 'TODO_UPDATE_REQUEST';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_UPDATE_ERROR = 'TODO_UPDATE_ERROR';
export const TODO_REMOVE_REQUEST = 'TODO_REMOVE_REQUEST';
export const TODO_REMOVE_SUCCESS = 'TODO_REMOVE_SUCCESS';
export const TODO_REMOVE_ERROR = 'TODO_REMOVE_ERROR';